version: '3.8'
services:
  backend:
    image: example-for-graduate-work
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/diplom

  frontend:
    image: ghcr.io/bizinmitya/front-react-avito:v1.21
    container_name: frontend
    ports:
      - 3000:3000

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 15432:5432
    user: root
    environment:
      POSTGRES_USER: work
      PGUSER: work
      POSTGRES_DB: diplom
      POSTGRES_PASSWORD: work
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d diplom -U work", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 10